# Generated by Django 4.2.30 on 2026-05-23 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('muscle_group', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('push', 'Push'), ('pull', 'Pull'), ('legs', 'Legs'), ('upper_arms', 'Upper/Arms'), ('conditioning_abs', 'Conditioning/Abs')], max_length=20)),
                ('equipment', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('machine', 'Machine'), ('cable', 'Cable'), ('bodyweight', 'Bodyweight')], max_length=20)),
                ('movement_type', models.CharField(choices=[('compound', 'Compound'), ('isolation', 'Isolation'), ('cardio', 'Cardio'), ('core', 'Core')], max_length=20)),
                ('default_min_reps', models.PositiveIntegerField(default=8)),
                ('default_max_reps', models.PositiveIntegerField(default=12)),
                ('default_sets', models.PositiveIntegerField(default=3)),
                ('default_increment', models.DecimalField(decimal_places=1, default=2.5, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='workouts.exercise')),
            ],
            options={
                'verbose_name_plural': 'exercise aliases',
                'unique_together': {('exercise', 'alias')},
            },
        ),
    ]
