# Generated by Django 4.2.30 on 2026-06-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_program_programday_programexercise'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programday',
            unique_together={('program', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='programexercise',
            unique_together={('program_day', 'exercise')},
        ),
    ]
