# Generated by Django 4.2.30 on 2026-06-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_programday_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='planned_rest_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
